name: "Chromatic"
on:
  pull_request_target:
    branches:
      - release/**
  push:
    branches:
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm i
      - name: build examples
        run: |
          NODE_OPTIONS="--openssl-legacy-provider" npm run build-storybook
      - name: upload storybook to chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook-static
